AWSTemplateFormatVersion: '2010-09-09'
Description: 'Despliegue de ECS Fargate con parámetros para VPC y Subnets'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Selecciona la VPC donde se desplegará el Security Group"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Selecciona al menos dos Subnets públicas para Fargate"

Resources:
  # 1. Registro de ECR
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "aws-ecs-simple-app"

  # 2. Cluster ECS
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "aws-ecs-simple-cluster"

  # 3. Rol de Ejecución IAM
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # 4. Grupo de Seguridad (Usa el parámetro VpcId)
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permitir entrada en puerto 5000"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  # 5. Definición de Tarea (Imagen base provisional)
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "aws-ecs-simple-app-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: "aws-ecs-simple-app"
          Image: "public.ecr.aws/docker/library/python:3.10-slim"
          PortMappings:
            - ContainerPort: 5000
          Command: ["python", "-m", "http.server", "5000"]
          Essential: true

  # 6. Servicio ECS (Usa el parámetro SubnetIds)
  MyService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: "aws-ecs-simple-service"
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: [!Ref MySecurityGroup]
          Subnets: !Ref SubnetIds